name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '7.0.x'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Set version from tag
      run: |
        tag_version="${GITHUB_REF##*/}"
        assembly_version="${tag_version}.0"
        file_version="${tag_version}.0"
        project_path="src/Micopy/Micopy.csproj"
        sed -i "s/<AssemblyVersion>[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*<\/AssemblyVersion>/<AssemblyVersion>${assembly_version}<\/AssemblyVersion>/g" $project_path
        sed -i "s/<FileVersion>[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*<\/FileVersion>/<FileVersion>${file_version}<\/FileVersion>/g" $project_path
        cat $project_path

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Micopy

    - name: Build application
      run: dotnet build --configuration Release --no-restore
      working-directory: src/Micopy

    - name: Publish application for Windows
      run: dotnet publish --configuration Release --no-restore --self-contained -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish/win-x64 --no-symbols
      working-directory: src/Micopy

    - name: Publish application for Linux
      run: dotnet publish --configuration Release --no-restore --self-contained -r linux-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish/linux-x64 --no-symbols
      working-directory: src/Micopy

    - name: Publish application for ARM
      run: dotnet publish --configuration Release --no-restore --self-contained -r linux-arm -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish/linux-arm --no-symbols
      working-directory: src/Micopy

    - name: Zip publish folders
      run: |
        sudo apt-get install zip
        zip -r publish/win-x64.zip publish/win-x64
        zip -r publish/linux-x64.zip publish/linux-x64
        zip -r publish/linux-arm.zip publish/linux-arm
        ls publish
      working-directory: src/Micopy


